# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Analytics for Chemistry
author: Alex Ganose
logo: logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: data-analytics-chemistry.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - refs.bib

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  thebe: true

# Information about where the book exists on the web
repository:
  url: https://github.com/utf/DataAnalyticsChemistry  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
  - dollarmath
  - amsmath
  - linkify
  - html_admonition
  - html_image
